apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-go
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
